version: '3.8'

services:
  duo-bypass-daemon:
    image: duo-telegram-bot:latest
    env_file:
      - .env
    volumes:
      - duo-bypass-data:/app/data
    restart: unless-stopped
    command: ["python", "/app/duo-bypass-daemon.py"]

volumes:
  duo-bypass-data:
    driver: local